# Generated by Django 5.2.8 on 2025-12-09 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_productimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
