# Generated by Django 5.2.8 on 2025-12-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0010_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='selected_color',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('Grey', 'Grey'), ('White', 'White'), ('Blue', 'Blue'), ('Brown', 'Brown'), ('DarkBlue', 'DarkBlue')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='selected_size',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=10, null=True),
        ),
    ]
