# Generated by Django 5.2.8 on 2025-12-19 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0012_remove_order_carts_alter_order_status_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Returned', 'Returned'), ('Cancelled', 'Cancelled'), ('Confirmed', 'Confirmed')], default='Pending', max_length=20),
        ),
    ]
