# Generated by Django 5.2.8 on 2025-12-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0014_alter_order_total_price_alter_order_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='selected_size',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], max_length=10, null=True),
        ),
    ]
